% Converte array de cells para tabela em csv (uma por ensaio)

clear; close all;

load('EnDataA.mat');

EnData = EnDataA; % Carrega os dados dos ensaios

loadTempoAmacA; % Carrega as estimativas de amaciamento

dest = 'D:\Documentos\Amaciamento\Apresentações\2021_03_26 - Nicolas (dados)\';

for k1 = 1:length(EnData)
    for k2 = 1:length(EnData{k1})
        temp = EnData{k1}(k2);
        name = strrep(temp.name(9:end),'\','_'); % Formata o nome do ensaio
        fname = [dest,name,'tAm',num2str(tEst{k1}(k2)),'.csv'];
        temp = rmfield(temp,'name');
        T = struct2table(temp);
        T.Properties.VariableNames = {'Tempo','PressaoDescarga','PressaoSuccao',...
                                      'CorrenteRMS','CorrenteCurtose','CorrenteAssimetria','CorrenteForma',...
                                      'CorrenteTHD','CorrentePico','CorrenteCrista','CorrenteVariancia',...
                                      'CorrenteDesvio',...
                                      'VibracaoCalotaInferiorRMS','VibracaoCalotaInferiorCurtose',...
                                      'VibracaoCalotaInferiorAssimetria','VibracaoCalotaInferiorForma',...
                                      'VibracaoCalotaInferiorTHD','VibracaoCalotaInferiorPico',...
                                      'VibracaoCalotaInferiorCrista','VibracaoCalotaInferiorVariancia',...
                                      'VibracaoCalotaInferiorDesvio',...
                                      'VibracaoCalotaSuperiorRMS','VibracaoCalotaSuperiorCurtose',...
                                      'VibracaoCalotaSuperiorAssimetria','VibracaoCalotaSuperiorForma',...
                                      'VibracaoCalotaSuperiorTHD','VibracaoCalotaSuperiorPico',...
                                      'VibracaoCalotaSuperiorCrista','VibracaoCalotaSuperiorVariancia',...
                                      'VibracaoCalotaSuperiorDesvio',...
                                      'Vazao'};
        writetable(T,fname);
    end
end